################################################################################
### 3rd-party repositories

- name: "dnf : Enable COPR repositories"
  become: true
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  with_items: 
    - nickavem/adw-gtk3

################################################################################
### Install packages

- name: "dnf : Install system utilities"
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - adw-gtk3-theme # libadwaita theme for GTK3 applications 
    - libgda # dependency for Pano Clipboard Manager
    - libgda-sqlite # dependency for Pano Clipboard Manager

- name: "dnf : Install applications"
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - evolution # Evolution Mail client
    - file-roller # archive manager
    - file-roller-nautilus # archive manager
    - gnome-tweaks # additional settings for GNOME
    - seahorse # keys & secrets manager

- name: "dnf : Uninstall unwanted applications"
  become: true
  dnf:
    name: "{{ item }}"
    state: absent
  with_items: 
    - libreoffice-core
    - rhythmbox