################################################################################
### Prerequisites

- name: "flatpaks : Add the flathub remote"
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

################################################################################
### Install packages

- name: "flatpaks : Install flatpaks"
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.gtk.Gtk3theme.adw-gtk3-dark # adw-gtk3 Theme
    - io.bassi.Amberol # Amberol (music player)
    - ca.desrt.dconf-editor # dconf Editor
    - com.mattjakeman.ExtensionManager # Extension Manager
    - org.gnome.Firmware # Firmware
    - com.github.johnfactotum.Foliate # Foliate (eBook reader)
    - io.github.nokse22.inspector # Inspector
    - io.missioncenter.MissionCenter # Mission Center (System Monitor)
    - org.gnome.World.PikaBackup # Pika Backup
    - io.github.alainm23.planify # Planify
    - org.gnome.PowerStats # Power Statistics
