################################################################################
### Prerequisites

- name: "flatpaks : Add the flathub remote"
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

################################################################################
### Install packages

- name: "flatpaks : Install flatpaks"
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - org.gtk.Gtk3theme.adw-gtk3-dark # adw-gtk3 Theme
    - io.bassi.Amberol # Amberol music player
    - com.usebottles.bottles # Bottles
    - ca.desrt.dconf-editor # dconf Editor
    - me.dusansimic.DynamicWallpaper # Dynamic Wallpaper Generator
    - com.mattjakeman.ExtensionManager # Extension Manager
    - org.gnome.Firmware # Firmware
    - io.github.nokse22.inspector # Inspector
    - org.gnome.World.PikaBackup # Pika Backup
    - org.gnome.PowerStats # Power Statistics