%YAML 1.3
---
- Rule:
  - Key: [Mouse Gesture Button, pressed]
  - KeyPress:
    - Super_L
    - click
...
---
- Rule:
  - Key: [Smart Shift, pressed]
  - KeyPress:
    - XF86_AudioPlay
    - click
...
