################################################################################
### Configure system environment variables

- name: "configs : Add Intel VAAPI driver config to /etc/profile.d"
  become: true
  copy:
    src: "{{ role_path }}/files/environment/intel-va-profile.sh"
    dest: "/etc/profile.d"
    owner: root
    group: root
