################################################################################
### Install packages

- name: "dnf : Install Intel Graphics dependencies & tools"
  become: true
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - mesa-dri-drivers # MESA graphics drivers
    - mesa-va-drivers # MESA graphics drivers
    - mesa-vdpau-drivers # MESA graphics drivers
    - mesa-vulkan-drivers # MESA graphics drivers
    - intel-compute-runtime # Intel compute API support
    - intel-gpu-firmware # Intel GPU firmware
    - intel-gpu-tools # Intel GPU tools
    - intel-level-zero # oneAPI L0 support (for Blender)
    - intel-media-driver # Intel media driver (VAAPI)
